apiVersion: v1
kind: Service
metadata:
  namespace: ingress
  name:  nginx-ingress
spec:
  type:  NodePort
  selector:
    name: nginx-ingress
  ports:
  - name:  http
    port:  80
    targetPort:  80
    protocol: TCP
  - name:  https
    port:  443
    targetPort:  443
    protocol: TCP